-- MySQL Script generated by MySQL Workbench
-- Thu May 16 12:28:12 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sibur_rfid
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sibur_rfid
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sibur_rfid` DEFAULT CHARACTER SET utf8 ;
USE `sibur_rfid` ;

-- -----------------------------------------------------
-- Table `sibur_rfid`.`shelf`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sibur_rfid`.`shelf` (
  `id_shelf` INT NOT NULL,
  `id_bookcase` INT NOT NULL,
  `number` INT NOT NULL,
  `id_antenna` INT NOT NULL,
  PRIMARY KEY (`id_shelf`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sibur_rfid`.`document`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sibur_rfid`.`document` (
  `id_document` INT(24) NOT NULL,
  `name_doc` VARCHAR(128) NOT NULL,
  `creation_date` DATE NOT NULL,
  `reference_shelf` INT NOT NULL,
  `current_shelf` INT NULL,
  PRIMARY KEY (`id_document`),
  INDEX `fk_document_shelf1_idx` (`reference_shelf` ASC) VISIBLE,
  INDEX `fk_document_shelf2_idx` (`current_shelf` ASC) VISIBLE,
  CONSTRAINT `fk_document_shelf1`
    FOREIGN KEY (`reference_shelf`)
    REFERENCES `sibur_rfid`.`shelf` (`id_shelf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_document_shelf2`
    FOREIGN KEY (`current_shelf`)
    REFERENCES `sibur_rfid`.`shelf` (`id_shelf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sibur_rfid`.`staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sibur_rfid`.`staff` (
  `id_staff` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `patronimic` VARCHAR(45) NOT NULL,
  `family_name` VARCHAR(45) NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(64) NOT NULL,
  `admin` TINYINT NOT NULL,
  `email` VARCHAR(128) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_staff`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sibur_rfid`.`log_record`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sibur_rfid`.`log_record` (
  `id_log_record` INT NOT NULL AUTO_INCREMENT,
  `action_date` TIMESTAMP NOT NULL,
  `action_log` ENUM('add', 'take', 'return') NOT NULL,
  `id_document` INT NOT NULL,
  `id_staff` INT NOT NULL,
  `id_shelf` INT NOT NULL,
  PRIMARY KEY (`id_log_record`),
  INDEX `fk_log_record_document_idx` (`id_document` ASC) VISIBLE,
  INDEX `fk_log_record_staff_idx` (`id_staff` ASC) VISIBLE,
  INDEX `fk_log_record_shelf_idx` (`id_shelf` ASC) VISIBLE,
  CONSTRAINT `fk_log_record_document`
    FOREIGN KEY (`id_document`)
    REFERENCES `sibur_rfid`.`document` (`id_document`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_log_record_staff`
    FOREIGN KEY (`id_staff`)
    REFERENCES `sibur_rfid`.`staff` (`id_staff`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_log_record_shelf`
    FOREIGN KEY (`id_shelf`)
    REFERENCES `sibur_rfid`.`shelf` (`id_shelf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `sibur_rfid` ;

-- -----------------------------------------------------
-- function add_document
-- -----------------------------------------------------

DELIMITER $$
USE `sibur_rfid`$$
CREATE DEFINER = 'sibur_rfid'@'localhost' function `add_document` (id INT(24), name_d char(128), creation_date DATETIME, ref_shelf int)
returns int
	IF (select * from document where document.id_document = id) is null then
		insert into document(id_document, name_doc, creation_date, reference_self, current_shelf) values (id, name_d, creation_date, ref_shelf, ref_shelf);
        return 0;
	else return 1;
	end if;$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure take
-- -----------------------------------------------------

DELIMITER $$
USE `sibur_rfid`$$
CREATE DEFINER = 'sibur_rfid'@'localhost' PROCEDURE `take` (IN id_doc inT, IN id_stuff INT)
BEGIN
	IF (SELECT * FROM document WHERE document.id_document = id_doc) IS NOT NULL THEN
    SELECT @tmp =  current_shelf FROM document WHERE document.id_document = id_doc;
		INSERT INTO log_record(action_log, id_document, id_shelf, id_staff) values ('take', id_doc, tmp, id_staff);
        update
        `document`
        set
        `currene_shelf` = null;
    ELSE SELECT NULL;
    END IF;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure returne
-- -----------------------------------------------------

DELIMITER $$
USE `sibur_rfid`$$
CREATE PROCEDURE `returne` ()
BEGIN

END$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
